apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-man-deliverable-role
rules:
- apiGroups: [
    "cert-manager.io"
    ]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-ns-rb
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-man-deliverable-role
subjects:
- kind: ServiceAccount
  name: system:serviceaccount:tsm:default