apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-catalog-info
  description: A sample catalog for Backstage
spec:
  targets:
    - ./components/java-web-app/tanzu-java-web-app.yaml
