apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: ./flux/apps/clusters/${cluster_name}
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tmc-tap

