apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deliverables
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
  - name: cluster-apps
    namespace: tanzu-continuousdelivery-resources
  interval: 10m0s
  path: flux/clusters/${cluster_name}/deliverables
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tmc-tap