---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: group-apps
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: ./flux/apps/clustergroups/costco-travel-tap
  prune: true
  postBuild:
    substitute:
      cluster_group: "costco-travel-tap"
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tmc-tap

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clustergroup-gitops
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
  - name: group-apps
    namespace: tanzu-continuousdelivery-resources
  interval: 10m0s
  path: flux/clustergroups/common/per-cluster
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-name-secret
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tmc-tap
