apiVersion: v1
kind: Secret
metadata:
 name: cert-man-recursive-ns
 namespace: tap-install
 annotations:
   kapp.k14s.io/change-group: "tap-overlays"
type: Opaque
stringData:
  cert-man-recursive-ns.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "cert-manager"}})
    ---
    apiVersion: apps/v1
    kind: Deployment
    spec:
      template:
        spec: 
          containers:
          #@overlay/match by="name"
          - name: cert-manager
            args:
            - --dns01-recursive-nameservers=10.220.136.2:53,10.220.136.2:53
            - --dns01-recursive-nameservers-only