apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-tsm
    apps.tanzu.vmware.com/workload-type: tsm
    apps.tanzu.vmware.com/has-tests: "true"
  name: tanzu-java-web-app-tsm
  namespace: dev
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/warroyo/tanzu-java-web-app-gitops
  params:
    - name: gitops_repository
      value: https://github.com/warroyo/tmc-tap
    - name: gitops_branch
      value: main
    - name: vhost
      value: tanzu-java-web-app.tsm.onprem.ct-tap.azure.warroyo.com
    - name: ports # modification
      value:
      - port: 80 # modification
        containerPort: 8080 # modification
        name: http # modification